import { 
    Menu,
    Search,
    CircleArrowRight,
    Heart,
    LayoutDashboard,
    TicketCheck,
    TramFront,
    ChevronsUpDown,
    LogOut,
    UserCircle2,
    PanelLeftIcon,
    ChevronDownIcon,
    ChevronUpIcon,
    Plus,
    Calendar,
    Package,
    IndianRupee,
    SquarePen,
    Trash2,
    Save,
    Image,
    Loader2,
    Upload,
    X,
    Bold,
    ListOrdered,
    List,
    Minus,
    Funnel,
    LayoutGrid,
    Ticket,
    CalendarDays,
    BadgeIndianRupee,
    BusFront,
    Hotel,
    Headset,
    ArrowRight,
    CheckCircle,
    CirclePlus,
    CircleX,
    CircleCheck,
    Phone,
    Clock,
    OctagonX,
    SearchX,
    MapPinned,
    Info,
    ArrowLeft,
    User,
    Calculator,
    CreditCard,
    FileText,
    MessageCircle,
    SquareArrowOutUpRight,
    TriangleAlert,
    Bell,
    Mail,
    MapPin,
    Users,
    ExternalLink,
    ChevronLeft,
    ChevronRight,
    Sparkles
} from "lucide-react"
import { FaceBookIcon, InstagramIcon, TwitterIcon, WhatsAppIcon, YouTubeIcon } from "./custom"


export const LUCIDE_ICON_MAP = {
    Menu,
    Search,
    CircleArrowRight,
    Heart,
    LayoutDashboard,
    TicketCheck,
    TramFront,
    ChevronsUpDown,
    LogOut,
    UserCircle2,
    PanelLeftIcon,
    ChevronDownIcon,
    ChevronUpIcon,
    Plus,
    Calendar,
    Package,
    IndianRupee,
    SquarePen,
    Trash2,
    Save,
    Image,
    Loader2,
    Upload,
    X,
    Bold,
    ListOrdered,
    List,
    Minus,
    Funnel,
    LayoutGrid,
    Ticket,
    CalendarDays,
    BadgeIndianRupee,
    BusFront,
    Hotel,
    Headset,
    ArrowRight,
    CheckCircle,
    CirclePlus,
    CircleX,
    CircleCheck,
    Phone,
    Clock,
    OctagonX,
    SearchX,
    MapPinned,
    Info,
    ArrowLeft,
    User,
    Calculator,
    CreditCard,
    FileText,
    MessageCircle,
    SquareArrowOutUpRight,
    TriangleAlert,
    Bell,
    Mail,
    MapPin,
    Users,
    ExternalLink,
    ChevronLeft,
    ChevronRight,
    Sparkles
}


export const CUSTOM_ICON_MAP = {
    whatspp: WhatsAppIcon,
    facebook: FaceBookIcon,
    twitter: TwitterIcon,
    instagram: InstagramIcon,
    youtube: YouTubeIcon
}