import { 
    Menu,
    Search,
    CircleArrowRight,
    Heart,
    LayoutDashboard,
    TicketCheck,
    TramFront,
    ChevronsUpDown,
    LogOut,
    UserCircle2,
    PanelLeftIcon,
    ChevronDownIcon,
    ChevronUpIcon,
    Plus,
    Calendar,
    Package,
    IndianRupee,
    SquarePen,
    Trash2,
    Save,
    Image,
    Loader2,
    Upload,
    X,
    Bold,
    ListOrdered,
    List,
    Minus,
    Funnel,
    LayoutGrid
} from "lucide-react"


export const LUCIDE_ICON_MAP = {
    Search: Search,
    Menu: Menu,
    CircleArrowRight: CircleArrowRight,
    Heart: Heart,
    LayoutDashboard: LayoutDashboard,
    TicketCheck: TicketCheck,
    TramFront: TramFront,
    ChevronsUpDown: ChevronsUpDown,
    LogOut: LogOut,
    UserCircle2: UserCircle2,
    PanelLeftIcon: PanelLeftIcon,
    ChevronDownIcon: ChevronDownIcon,
    ChevronUpIcon: ChevronUpIcon,
    Plus: Plus,
    Calendar: Calendar,
    Package: Package,
    IndianRupee: IndianRupee,
    SquarePen: SquarePen,
    Trash2: Trash2,
    Save: Save,
    Image: Image,
    Loader2: Loader2,
    Upload: Upload,
    X: X,
    Bold: Bold,
    ListOrdered: ListOrdered,
    List: List,
    Minus: Minus,
    Funnel: Funnel,
    LayoutGrid: LayoutGrid,
}